modLoader="javafml" 
loaderVersion="[33,)"
issueTrackerURL="https://github.com/owmii/krate/issues"
license="LGPLv3"

[[mods]]
modId="krate"
version="${file.jarVersion}"
displayName="Krate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/krate"
authors="owmii"
description='''
Krate, a storage mod ;).
'''

[[dependencies.krate]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krate]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.3,)"
    ordering="NONE"
    side="BOTH"