modLoader="javafml" 
loaderVersion="[35,)"
issueTrackerURL="https://github.com/owmii/krate/issues"
license="LGPLv3"

[[mods]]
modId="krate"
version="${file.jarVersion}"
displayName="Krate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/krate"
authors="owmii"
description='''
Better than chest with filters and useful upgrades.
'''

[[dependencies.krate]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.2.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krate]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.2,)"
    ordering="NONE"
    side="BOTH"