modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/owmii/krate/issues"
license="LGPLv3"

[[mods]]
modId="krate"
version="${file.jarVersion}"
displayName="Krate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/krate"
authors="owmii"
description='''
Better than chest with filters and useful upgrades.
'''

[[dependencies.krate]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.2.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krate]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    ordering="NONE"
    side="BOTH"